on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Doing test deploy to Pinata
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Pinata deploy action step
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.3.8
        with:
          pin-name: 'TESTING (v1.3.8)'
          path: './build'
          pinata-api-key: ${{ secrets.IPFS_PINATA_DEPLOY_ACTION_API_KEY }}
          pinata-secret-api-key: ${{ secrets.IPFS_PINATA_DEPLOY_ACTION_API_SECRET_KEY }}
      # Use the output from the `deploy` step
      - name: Get the output hash
        run: echo "The hash was ${{ steps.deploy.outputs.hash }}"